apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flow-control
data:
  myvalue: "Hello Helm"
  drink: {{ .Values.favoriteDrink | default "tea" | quote}}
  {{- if eq .Values.favoriteDrink "coffee" }}
  mug: "true"
  {{- end }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
  size: |-
    {{- range tuple "small" "medium" "large" }}
    - {{ . }}
    {{- end }}
